name: Setup Test Environment
description: "Install uv, use uv to install dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
          version: "0.5.4"

    - name: python setup
      shell: bash
      run: uv python install

    - name: install project
      shell: bash
      run: uv sync --all-extras --dev
