name: Setup Test Environment
description: "Install poetry, use poetry to install dependencies"

runs:
  using: "composite"
  steps:
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --no-interaction --without release,dev,lsp
      shell: bash
