# PR template configuration
pull_request_template:
  path: .github/PULL_REQUEST_TEMPLATE.yml

# Additional repository settings
repository:
  # Ensure PRs are always up to date before merging
  allow_merge_commit: false
  allow_squash_merge: false
  allow_rebase_merge: true
