[[plugins]]
name = "skeleton"
target_platform = "elastic-node-v5-spartan7-xc15"
target_runtime = "vhdl"
version = "0.1"
api_version = "0.1"
templates = ["skeleton"]
static_files = ["skeleton_pkg.vhd"]
