[[plugins]]
name = "mac_delta"
version = "0.1"
api_version = "0.1"
target_runtime = "verilog"
target_platform = "FPGA"
generated = ["mac_delta_array", "mac_delta_bram"]
static_files = ["mac_delta_core.v"]
