import pytest

from torchvision.models import resnet18

from elasticai.creator import ir
from elasticai.creator.torch2ir import (
    Torch2Ir as Torch2IrTranslator,
)
from elasticai.creator.torch2ir.default_handlers import (
    adaptiveavgpool2d,
    add,
    batchnorm1d,
    batchnorm2d,
    conv2d,
    flatten,
    linear,
    maxpool2d,
    relu,
)


def big_model():
    return resnet18(pretrained=True)


def convert(model):
    translate = Torch2IrTranslator()
    translate.register()(flatten)
    translate.register()(linear)
    translate.register()(relu)
    translate.register()(batchnorm1d)
    translate.register()(conv2d)
    translate.register()(maxpool2d)
    translate.register()(batchnorm2d)
    translate.register()(adaptiveavgpool2d)
    translate.register()(add)

    serializer = ir.IrSerializerLegacy()

    root, reg = translate(model)
    result = {k: serializer.serialize(reg[k]) for k in reg}
    result[""] = serializer.serialize(root)
    return result


@pytest.mark.slow
def test_convert_resnet_to_ir():
    m = big_model()
    ir = convert(m)
    assert ir == {
        "conv1": {
            "type": "conv2d",
            "in_channels": 3,
            "out_channels": 64,
            "kernel_size": (7, 7),
            "stride": (2, 2),
            "padding": (3, 3),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "bn1": {
            "type": "batchnorm2d",
            "num_features": 64,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "relu": {"type": "relu", "nodes": {}, "edges": {}},
        "maxpool": {
            "type": "maxpool2d",
            "kernel_size": 3,
            "stride": 2,
            "padding": 1,
            "dilation": 1,
            "nodes": {},
            "edges": {},
        },
        "layer1.0.conv1": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 64,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer1.0.bn1": {
            "type": "batchnorm2d",
            "num_features": 64,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer1.0.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer1.0.conv2": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 64,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer1.0.bn2": {
            "type": "batchnorm2d",
            "num_features": 64,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "add": {"type": "add", "nodes": {}, "edges": {}},
        "layer1.1.conv1": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 64,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer1.1.bn1": {
            "type": "batchnorm2d",
            "num_features": 64,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer1.1.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer1.1.conv2": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 64,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer1.1.bn2": {
            "type": "batchnorm2d",
            "num_features": 64,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer2.0.conv1": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 128,
            "kernel_size": (3, 3),
            "stride": (2, 2),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer2.0.bn1": {
            "type": "batchnorm2d",
            "num_features": 128,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer2.0.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer2.0.conv2": {
            "type": "conv2d",
            "in_channels": 128,
            "out_channels": 128,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer2.0.bn2": {
            "type": "batchnorm2d",
            "num_features": 128,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer2.0.downsample.0": {
            "type": "conv2d",
            "in_channels": 64,
            "out_channels": 128,
            "kernel_size": (1, 1),
            "stride": (2, 2),
            "padding": (0, 0),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer2.0.downsample.1": {
            "type": "batchnorm2d",
            "num_features": 128,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer2.1.conv1": {
            "type": "conv2d",
            "in_channels": 128,
            "out_channels": 128,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer2.1.bn1": {
            "type": "batchnorm2d",
            "num_features": 128,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer2.1.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer2.1.conv2": {
            "type": "conv2d",
            "in_channels": 128,
            "out_channels": 128,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer2.1.bn2": {
            "type": "batchnorm2d",
            "num_features": 128,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer3.0.conv1": {
            "type": "conv2d",
            "in_channels": 128,
            "out_channels": 256,
            "kernel_size": (3, 3),
            "stride": (2, 2),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer3.0.bn1": {
            "type": "batchnorm2d",
            "num_features": 256,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer3.0.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer3.0.conv2": {
            "type": "conv2d",
            "in_channels": 256,
            "out_channels": 256,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer3.0.bn2": {
            "type": "batchnorm2d",
            "num_features": 256,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer3.0.downsample.0": {
            "type": "conv2d",
            "in_channels": 128,
            "out_channels": 256,
            "kernel_size": (1, 1),
            "stride": (2, 2),
            "padding": (0, 0),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer3.0.downsample.1": {
            "type": "batchnorm2d",
            "num_features": 256,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer3.1.conv1": {
            "type": "conv2d",
            "in_channels": 256,
            "out_channels": 256,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer3.1.bn1": {
            "type": "batchnorm2d",
            "num_features": 256,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer3.1.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer3.1.conv2": {
            "type": "conv2d",
            "in_channels": 256,
            "out_channels": 256,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer3.1.bn2": {
            "type": "batchnorm2d",
            "num_features": 256,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer4.0.conv1": {
            "type": "conv2d",
            "in_channels": 256,
            "out_channels": 512,
            "kernel_size": (3, 3),
            "stride": (2, 2),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer4.0.bn1": {
            "type": "batchnorm2d",
            "num_features": 512,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer4.0.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer4.0.conv2": {
            "type": "conv2d",
            "in_channels": 512,
            "out_channels": 512,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer4.0.bn2": {
            "type": "batchnorm2d",
            "num_features": 512,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer4.0.downsample.0": {
            "type": "conv2d",
            "in_channels": 256,
            "out_channels": 512,
            "kernel_size": (1, 1),
            "stride": (2, 2),
            "padding": (0, 0),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer4.0.downsample.1": {
            "type": "batchnorm2d",
            "num_features": 512,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer4.1.conv1": {
            "type": "conv2d",
            "in_channels": 512,
            "out_channels": 512,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer4.1.bn1": {
            "type": "batchnorm2d",
            "num_features": 512,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "layer4.1.relu": {"type": "relu", "nodes": {}, "edges": {}},
        "layer4.1.conv2": {
            "type": "conv2d",
            "in_channels": 512,
            "out_channels": 512,
            "kernel_size": (3, 3),
            "stride": (1, 1),
            "padding": (1, 1),
            "dilation": (1, 1),
            "groups": 1,
            "bias": False,
            "padding_mode": "zeros",
            "nodes": {},
            "edges": {},
        },
        "layer4.1.bn2": {
            "type": "batchnorm2d",
            "num_features": 512,
            "affine": True,
            "nodes": {},
            "edges": {},
        },
        "avgpool": {
            "type": "adaptiveavgpool2d",
            "output_size": (1, 1),
            "nodes": {},
            "edges": {},
        },
        "flatten": {"type": "flatten", "nodes": {}, "edges": {}},
        "fc": {
            "type": "linear",
            "in_features": 512,
            "out_features": 1000,
            "bias": True,
            "nodes": {},
            "edges": {},
        },
        "": {
            "type": "module",
            "nodes": {
                "x": {"type": "input", "implementation": "input"},
                "conv1": {"type": "conv2d", "implementation": "conv1"},
                "bn1": {"type": "batchnorm2d", "implementation": "bn1"},
                "relu": {"type": "relu", "implementation": "relu"},
                "maxpool": {"type": "maxpool2d", "implementation": "maxpool"},
                "layer1_0_conv1": {
                    "type": "conv2d",
                    "implementation": "layer1.0.conv1",
                },
                "add": {"type": "add", "implementation": "add"},
                "layer1_0_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer1.0.bn1",
                },
                "layer1_0_relu": {"type": "relu", "implementation": "layer1.0.relu"},
                "layer1_0_conv2": {
                    "type": "conv2d",
                    "implementation": "layer1.0.conv2",
                },
                "layer1_0_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer1.0.bn2",
                },
                "layer1_0_relu_1": {"type": "relu", "implementation": "layer1.0.relu"},
                "layer1_1_conv1": {
                    "type": "conv2d",
                    "implementation": "layer1.1.conv1",
                },
                "add_1": {"type": "add", "implementation": "add"},
                "layer1_1_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer1.1.bn1",
                },
                "layer1_1_relu": {"type": "relu", "implementation": "layer1.1.relu"},
                "layer1_1_conv2": {
                    "type": "conv2d",
                    "implementation": "layer1.1.conv2",
                },
                "layer1_1_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer1.1.bn2",
                },
                "layer1_1_relu_1": {"type": "relu", "implementation": "layer1.1.relu"},
                "layer2_0_conv1": {
                    "type": "conv2d",
                    "implementation": "layer2.0.conv1",
                },
                "layer2_0_downsample_0": {
                    "type": "conv2d",
                    "implementation": "layer2.0.downsample.0",
                },
                "layer2_0_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer2.0.bn1",
                },
                "layer2_0_relu": {"type": "relu", "implementation": "layer2.0.relu"},
                "layer2_0_conv2": {
                    "type": "conv2d",
                    "implementation": "layer2.0.conv2",
                },
                "layer2_0_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer2.0.bn2",
                },
                "add_2": {"type": "add", "implementation": "add"},
                "layer2_0_downsample_1": {
                    "type": "batchnorm2d",
                    "implementation": "layer2.0.downsample.1",
                },
                "layer2_0_relu_1": {"type": "relu", "implementation": "layer2.0.relu"},
                "layer2_1_conv1": {
                    "type": "conv2d",
                    "implementation": "layer2.1.conv1",
                },
                "add_3": {"type": "add", "implementation": "add"},
                "layer2_1_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer2.1.bn1",
                },
                "layer2_1_relu": {"type": "relu", "implementation": "layer2.1.relu"},
                "layer2_1_conv2": {
                    "type": "conv2d",
                    "implementation": "layer2.1.conv2",
                },
                "layer2_1_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer2.1.bn2",
                },
                "layer2_1_relu_1": {"type": "relu", "implementation": "layer2.1.relu"},
                "layer3_0_conv1": {
                    "type": "conv2d",
                    "implementation": "layer3.0.conv1",
                },
                "layer3_0_downsample_0": {
                    "type": "conv2d",
                    "implementation": "layer3.0.downsample.0",
                },
                "layer3_0_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer3.0.bn1",
                },
                "layer3_0_relu": {"type": "relu", "implementation": "layer3.0.relu"},
                "layer3_0_conv2": {
                    "type": "conv2d",
                    "implementation": "layer3.0.conv2",
                },
                "layer3_0_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer3.0.bn2",
                },
                "add_4": {"type": "add", "implementation": "add"},
                "layer3_0_downsample_1": {
                    "type": "batchnorm2d",
                    "implementation": "layer3.0.downsample.1",
                },
                "layer3_0_relu_1": {"type": "relu", "implementation": "layer3.0.relu"},
                "layer3_1_conv1": {
                    "type": "conv2d",
                    "implementation": "layer3.1.conv1",
                },
                "add_5": {"type": "add", "implementation": "add"},
                "layer3_1_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer3.1.bn1",
                },
                "layer3_1_relu": {"type": "relu", "implementation": "layer3.1.relu"},
                "layer3_1_conv2": {
                    "type": "conv2d",
                    "implementation": "layer3.1.conv2",
                },
                "layer3_1_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer3.1.bn2",
                },
                "layer3_1_relu_1": {"type": "relu", "implementation": "layer3.1.relu"},
                "layer4_0_conv1": {
                    "type": "conv2d",
                    "implementation": "layer4.0.conv1",
                },
                "layer4_0_downsample_0": {
                    "type": "conv2d",
                    "implementation": "layer4.0.downsample.0",
                },
                "layer4_0_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer4.0.bn1",
                },
                "layer4_0_relu": {"type": "relu", "implementation": "layer4.0.relu"},
                "layer4_0_conv2": {
                    "type": "conv2d",
                    "implementation": "layer4.0.conv2",
                },
                "layer4_0_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer4.0.bn2",
                },
                "add_6": {"type": "add", "implementation": "add"},
                "layer4_0_downsample_1": {
                    "type": "batchnorm2d",
                    "implementation": "layer4.0.downsample.1",
                },
                "layer4_0_relu_1": {"type": "relu", "implementation": "layer4.0.relu"},
                "layer4_1_conv1": {
                    "type": "conv2d",
                    "implementation": "layer4.1.conv1",
                },
                "add_7": {"type": "add", "implementation": "add"},
                "layer4_1_bn1": {
                    "type": "batchnorm2d",
                    "implementation": "layer4.1.bn1",
                },
                "layer4_1_relu": {"type": "relu", "implementation": "layer4.1.relu"},
                "layer4_1_conv2": {
                    "type": "conv2d",
                    "implementation": "layer4.1.conv2",
                },
                "layer4_1_bn2": {
                    "type": "batchnorm2d",
                    "implementation": "layer4.1.bn2",
                },
                "layer4_1_relu_1": {"type": "relu", "implementation": "layer4.1.relu"},
                "avgpool": {"type": "adaptiveavgpool2d", "implementation": "avgpool"},
                "flatten": {"type": "flatten", "implementation": "flatten"},
                "fc": {"type": "linear", "implementation": "fc"},
                "output": {"type": "output", "implementation": "output"},
            },
            "edges": {
                "x": {"conv1": {}},
                "conv1": {"bn1": {}},
                "bn1": {"relu": {}},
                "relu": {"maxpool": {}},
                "maxpool": {"layer1_0_conv1": {}, "add": {}},
                "layer1_0_conv1": {"layer1_0_bn1": {}},
                "add": {"layer1_0_relu_1": {}},
                "layer1_0_bn1": {"layer1_0_relu": {}},
                "layer1_0_relu": {"layer1_0_conv2": {}},
                "layer1_0_conv2": {"layer1_0_bn2": {}},
                "layer1_0_bn2": {"add": {}},
                "layer1_0_relu_1": {"layer1_1_conv1": {}, "add_1": {}},
                "layer1_1_conv1": {"layer1_1_bn1": {}},
                "add_1": {"layer1_1_relu_1": {}},
                "layer1_1_bn1": {"layer1_1_relu": {}},
                "layer1_1_relu": {"layer1_1_conv2": {}},
                "layer1_1_conv2": {"layer1_1_bn2": {}},
                "layer1_1_bn2": {"add_1": {}},
                "layer1_1_relu_1": {"layer2_0_conv1": {}, "layer2_0_downsample_0": {}},
                "layer2_0_conv1": {"layer2_0_bn1": {}},
                "layer2_0_downsample_0": {"layer2_0_downsample_1": {}},
                "layer2_0_bn1": {"layer2_0_relu": {}},
                "layer2_0_relu": {"layer2_0_conv2": {}},
                "layer2_0_conv2": {"layer2_0_bn2": {}},
                "layer2_0_bn2": {"add_2": {}},
                "add_2": {"layer2_0_relu_1": {}},
                "layer2_0_downsample_1": {"add_2": {}},
                "layer2_0_relu_1": {"layer2_1_conv1": {}, "add_3": {}},
                "layer2_1_conv1": {"layer2_1_bn1": {}},
                "add_3": {"layer2_1_relu_1": {}},
                "layer2_1_bn1": {"layer2_1_relu": {}},
                "layer2_1_relu": {"layer2_1_conv2": {}},
                "layer2_1_conv2": {"layer2_1_bn2": {}},
                "layer2_1_bn2": {"add_3": {}},
                "layer2_1_relu_1": {"layer3_0_conv1": {}, "layer3_0_downsample_0": {}},
                "layer3_0_conv1": {"layer3_0_bn1": {}},
                "layer3_0_downsample_0": {"layer3_0_downsample_1": {}},
                "layer3_0_bn1": {"layer3_0_relu": {}},
                "layer3_0_relu": {"layer3_0_conv2": {}},
                "layer3_0_conv2": {"layer3_0_bn2": {}},
                "layer3_0_bn2": {"add_4": {}},
                "add_4": {"layer3_0_relu_1": {}},
                "layer3_0_downsample_1": {"add_4": {}},
                "layer3_0_relu_1": {"layer3_1_conv1": {}, "add_5": {}},
                "layer3_1_conv1": {"layer3_1_bn1": {}},
                "add_5": {"layer3_1_relu_1": {}},
                "layer3_1_bn1": {"layer3_1_relu": {}},
                "layer3_1_relu": {"layer3_1_conv2": {}},
                "layer3_1_conv2": {"layer3_1_bn2": {}},
                "layer3_1_bn2": {"add_5": {}},
                "layer3_1_relu_1": {"layer4_0_conv1": {}, "layer4_0_downsample_0": {}},
                "layer4_0_conv1": {"layer4_0_bn1": {}},
                "layer4_0_downsample_0": {"layer4_0_downsample_1": {}},
                "layer4_0_bn1": {"layer4_0_relu": {}},
                "layer4_0_relu": {"layer4_0_conv2": {}},
                "layer4_0_conv2": {"layer4_0_bn2": {}},
                "layer4_0_bn2": {"add_6": {}},
                "add_6": {"layer4_0_relu_1": {}},
                "layer4_0_downsample_1": {"add_6": {}},
                "layer4_0_relu_1": {"layer4_1_conv1": {}, "add_7": {}},
                "layer4_1_conv1": {"layer4_1_bn1": {}},
                "add_7": {"layer4_1_relu_1": {}},
                "layer4_1_bn1": {"layer4_1_relu": {}},
                "layer4_1_relu": {"layer4_1_conv2": {}},
                "layer4_1_conv2": {"layer4_1_bn2": {}},
                "layer4_1_bn2": {"add_7": {}},
                "layer4_1_relu_1": {"avgpool": {}},
                "avgpool": {"flatten": {}},
                "flatten": {"fc": {}},
                "fc": {"output": {}},
                "output": {},
            },
        },
    }
