name: "Prepare Devenv"
description: "Prepare the development environment using devenv shell"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - run: nix profile install nixpkgs#devenv
      shell: bash
    - run: devenv shell
      shell: bash
