name: "Prepare Devenv"
description: "Prepare the development environment using devenv shell"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v15
      with:
        name: devenv
    - run: nix profile install nixpkgs/nixos-24.11#devenv
      shell: bash
    - run: devenv shell
      shell: bash
