
[[plugins]]
name = 'padding'
version = '0.1'
api_version = '0.1'
target_runtime = 'vhdl'
target_platform = ''
generated = []
static_files = [
  "padding_pkg.vhd",
  "dynamic_padder.vhd",
  "dynamic_padding_remover.vhd",
  "fifo_buffer.vhd",
]

