[[plugins]]
name = 'act_func'
version = '0.1'
api_version = '0.1'
target_runtime = 'verilog'
target_platform = 'FPGA'
generated = ["absolute", "hardtanh", "heaviside", "precomputed", "relu", "prelu", "sign"]
static_files = []
