name: Semantic Release

on:
  push:
    branches:
      - ci-cd

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TEST_ACCOUNT_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/